### ISSUE TITLE
会話ダイアログが大量に出て進行できない

### ISSUE THREAD

**Issue by eai04191** [laineus/unsung-kingdom#2]
https://i.imgur.com/Pb91s8F.mp4

unsungkingdom.laineus.com/app.html と現時点のmasterブランチのdevビルドで確認しました。

## 環境
Google Chrome 83.0.4103.116 Windows 64bit
Firefox 77.0.1 Windows 64bit

**Comment by laineus** [comment]
@eai04191 

起票ありがとうございます！
これは致命的ですね。。

僕のChrome 83では発生したことがない問題ですが、あとで調査させていただきます。

**Comment by eai04191** [comment]
対応ありがとうございます
デバック情報の提供など、こちらでなにか協力できることがあればおしらせください。

**Comment by laineus** [comment]
@eai04191 
おかげさまで修正が完了しました！

恐らくマシンの処理速度（？）に影響される問題で、
僕のほうでは結局再現できなかったんですが、恐らくこれで直ったはずです。
https://github.com/laineus/unsung-kingdom/pull/4

本番のjsも更新済みです。

**Comment by eai04191** [comment]
対応お疲れさまです。こちらでも問題なくプレイできることを確認できました。

**Comment by laineus** [comment]
よかったです！ありがとうございました！
